### ISSUE TITLE
ik mis nog highscores e.d.

### ISSUE THREAD

**Issue by stgm** [Lirry/JackThePirate#1]

**Comment by Lirry** [comment]
Bedoel je in de sketch? Want in de tekst staat het onder kopje 4. "De game bestaat uit verschillende activities. In de main-activity kan er gekozen worden tussen levels, highscores (in tijd), settings en exit"

**Comment by stgm** [comment]
Ja, ook, maar ook in zo'n zin is het niet heel overzichtelijk. Loop me echt even door de app heen in je proposal.
